SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B
INNER JOIN AUTHOR A
    ON B.AUTHOR_ID = A.AUTHOR_ID
INNER JOIN BOOK_SALES S
    ON B.BOOK_ID = S.BOOK_ID
WHERE YEAR(S.SALES_DATE) = '2022'
    AND MONTH(S.SALES_DATE) = '01'
-- (저자ID, 저자명, 카테고리) -> 한 세트
GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC;