SELECT R.HISTORY_ID, 
    ROUND(
        C.DAILY_FEE 
        * (DATEDIFF(R.END_DATE, R.START_DATE) + 1) 
        * (100 - IFNULL(D.DISCOUNT_RATE, 0)) / 100
    ) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C 
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY R
    ON C.CAR_ID = R.CAR_ID
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON C.CAR_TYPE = D.CAR_TYPE
    AND D.DURATION_TYPE = 
        CASE 
            WHEN DATEDIFF(R.END_DATE, R.START_DATE) + 1 >= 90
                THEN '90일 이상'
            WHEN DATEDIFF(R.END_DATE, R.START_DATE) + 1 >= 30
                THEN '30일 이상'
            WHEN DATEDIFF(R.END_DATE, R.START_DATE) + 1 >= 7
                THEN '7일 이상'
            END
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, R.HISTORY_ID DESC;