WITH RECURSIVE A AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM A
    WHERE HOUR < 23
)
SELECT A.HOUR, COUNT(B.ANIMAL_ID) AS COUNT
FROM A
LEFT JOIN ANIMAL_OUTS B
    ON A.HOUR = HOUR(B.DATETIME)
GROUP BY A.HOUR
ORDER BY A.HOUR ASC;