SELECT MEMBER_ID,
    MEMBER_NAME,
    GENDER,
    -- (주의사항) DATE_OF_BIRTH의 데이트 포맷이 예시와 동일해야 정답처리 됩니다.
    DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d')
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH) = 3
    AND GENDER = 'W'
    AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;