SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOATL_SALES
FROM USED_GOODS_BOARD B
INNER JOIN USED_GOODS_USER U
    ON B.WRITER_ID = U.USER_ID
WHERE STATUS = 'DONE'
GROUP BY U.USER_ID, U.NICKNAME
HAVING SUM(B.PRICE) >= 700000
ORDER BY SUM(B.PRICE) ASC;