# Python, C#을 모두 가진 개발자 중복 방지 -> DISTINCT
SELECT DISTINCT ID,
    EMAIL,
    FIRST_NAME,
    LAST_NAME
FROM SKILLCODES S
INNER JOIN DEVELOPERS D
    ON D.SKILL_CODE & S.CODE > 0
WHERE S.NAME IN ('Python', 'C#')
ORDER BY ID;