SELECT YEAR(A.DIFFERENTIATION_DATE), 
    (SELECT MAX(SIZE_OF_COLONY) FROM ECOLI_DATA B
        WHERE YEAR(A.DIFFERENTIATION_DATE) = YEAR(B.DIFFERENTIATION_DATE)) 
        - A.SIZE_OF_COLONY
        AS YEAR_DEV, 
    A.ID
FROM ECOLI_DATA A
ORDER BY YEAR(A.DIFFERENTIATION_DATE) ASC, YEAR_DEV ASC;