SELECT B.CATEGORY,
    SUM(A.SALES) AS TOTAL_SALES
FROM BOOK_SALES A
INNER JOIN BOOK B
    ON A.BOOK_ID = B.BOOK_ID
WHERE A.SALES_DATE BETWEEN '2022-01-01'
    AND '2022-01-31'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;